### ISSUE TITLE
what does the output log show?

### ISSUE THREAD

**Issue by rumschuettel** [msr-quarc/Liquid#17]
Not a bug, but out of curiosity:
`
0:0015.1/Time:   191 [180 to 240] MB=      61 cache(22973,16) GC:1478
`
What are the numbers after `cache`? I assume the last line is the garbage collected gates, but I can't see what the other numbers mean: I'm not caching gates, but yet the number is increasing constantly. Disabling the cache by setting `CacheDisable` to `true` does not change the output.

Hope someone can help clarifying that :-).
Thanks & best,
rumschuettel

**Comment by dbwz8** [comment]
The first number is how many gate hits there were in the cache. Note that several built-in gates are automatically cached. The second number is the number of gates that were not found in the cache. This would be the first time the built-in gates were called... so there are 16 of them that are cached. Calling `CacheDisable` prevents new gates from being added to the cache (it does not turn the cache off). The only reason to do this is if you have gates with the same name that do different things (causing a cache conflict). The last number is the number of Generation 0 and Generation 1 Garbage Collections that have been called since the last time it was reported.

**Comment by rumschuettel** [comment]
Great, super helpful! Thanks Dave!

2016-03-16 22:42 GMT+00:00 Dave Wecker <notifications@github.com>:

**Comment by dbwz8** [comment]
(answered)
