### ISSUE TITLE
Tutorial.mht does not open correctly

### ISSUE THREAD

**Issue by stuartah** [msr-quarc/Liquid#8]
I can't seem to get Tutorial.mht to open as a webpage.

Just updated to IE11 and same problem - opens as text - possible html error?

**Comment by alan-geller** [comment]
GitHub by default displays all files in their raw text, wrapped inside a formatted window; that's why it's displayed as text.
I've rewritten the document into a GitHub markdown document, tutorial.md, which is rendered properly within GitHub.
As an aside, this document is **not** a stand-alone LIQUi|> tutorial; rather, it's a rough outline of the [tutorial video](http://research.microsoft.com/apps/video/default.aspx?id=258279). The [Getting Started guide](https://github.com/msr-quarc/Liquid/blob/master/GettingStarted.md) is a better stand-alone intro, and the first few chapters of the [user's manual](https://github.com/msr-quarc/Liquid/blob/master/docs/LIQUiD.pdf) are a more detailed introduction.

I'm going to mark this issue as closed. Please re-open it if the tutorial.md page doesn't display properly for you, and thanks for your interest in LIQUi|>!!

**Comment by stuartah** [comment]
Thanks Alan.

I can view the file now so the issue is definitely resolved.

I am excited to start using Liqui|> over the next couple week. If I do
encounter any bugs or issues, is there a better place to report them?

Thanks,
Stuart

**Comment by alan-geller** [comment]
Stuart,

This is the best place to report a problem or ask a question.

Thanks!!

Alan

**Comment by stuartah** [comment]
Thanks Alan.

I'm also curious about Liquid performance. I have just reinstalled Liquid
on my local machine and *the included basic tests run surprisingly
slow *(running
via command prompt). I am currently running Windows 7 on a local VM -
previously I ran the same tests via a MS Azure VM install and did not have
this problem.

Is there any obvious setting adjustments or optimizations to fix this? Or
could the issue be insufficient resources allocated to my VM? (other
windows programs have no noticeable slowdown)
Have you guy released a required resources spec?

Thanks,
Stuart

**Comment by alan-geller** [comment]
Stuart,
We don't have a resources required spec, I'm afraid. Most of the tests will run fine on a dual-core (more cores are better, LIQUi|> is multithreaded). Also, of course, you need enough memory to keep the state vector and unitaries in memory. You might want to check to see if your VM is running out of memory, or perhaps if it's just got a single core.
Alan
